# SPDX-FileCopyrightText: 2024 Imran Mustafa <imran@imranmustafa.net>
# SPDX-License-Identifier: GPL-3.0-or-later
* Pong
It's pong that's it.
** Usage
This is made with [[https://love2d.org/][LÖVE]], so usage is similar to other games made with the
engine. Just run the =love= command in the directory containing =main.lua=,
which will run the game.
#+begin_src sh
love .
#+end_src
** Gameplay
The left hand paddle can be move up with =w= and down with =s=, likewise the
right hand paddle is moved with =↑= and =↓=. You can also press =r= to reset the
ball to the centre of the screen.
* Copyright/Licensing
Copyright (C) 2024 Imran Mustafa

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see <https://www.gnu.org/licenses/>.
